### ISSUE TITLE
inheritFromWidgetOfExactType is deprecated use dependOnInheritedWidgetOfExactType instead

### ISSUE THREAD

**Issue by tlueder** [Sub6Resources/chewie_audio#11]
Change lib/src/chewie_player.dart line 99

From:
   context.inheritFromWidgetOfExactType(_ChewieAudioControllerProvider) as _ChewieAudioControllerProvider;

To:
  context.dependOnInheritedWidgetOfExactType<_ChewieAudioControllerProvider>() as _ChewieAudioControllerProvider;

**Comment by britannio** [comment]
@tlueder Are you making a PR for this?

**Comment by tlueder** [comment]
@britannio no need.

I just saw it is already fixed in master, but not yet released.
