### ISSUE TITLE
Build error on master because of removed method inheritFromWidgetOfExactType

### ISSUE THREAD

**Issue by sma** [Sub6Resources/chewie_audio#9]
Version 1.1.1 doesn't build anymore on master because of of https://github.com/flutter/flutter/pull/69620

The method `inheritFromWidgetOfExactType` is no longer just deprecated but removed from the code base.

**Comment by Shvet** [comment]
I am getting error in flutter_html too. any solution?

**Comment by EHBradford** [comment]
I am getting this error from flutter_html.  Blocking me from building my project for around 2 weeks now.

**Comment by Shvet** [comment]
@EHBradford have you upgraded your flutter sdk? they have removed few deprecated methods and it is making errors! Check out above comments.
